//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\crich\Documents\Coding\Fractals\BoxRayTracer\Antlr\BRTSettingsTest.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BRTSettingsTestParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IBRTSettingsTestVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] BRTSettingsTestParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.setting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetting([NotNull] BRTSettingsTestParser.SettingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKey([NotNull] BRTSettingsTestParser.KeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] BRTSettingsTestParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.primitive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitive([NotNull] BRTSettingsTestParser.PrimitiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] BRTSettingsTestParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.vector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVector([NotNull] BRTSettingsTestParser.VectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BRTSettingsTestParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] BRTSettingsTestParser.ListContext context);
}
